spring:
  application:
    name: exchange-order
  cloud:
    nacos:
      config:
        import-check:
          enabled: false

mybatis:
  type-aliases-package: open.vincentf13.exchange.order.infra.persistence.po

open:
  vincentf13:
    id-generator:
      snowflake:
        worker-id: 3
    mybatis:
      mapper-base-packages: open.vincentf13.exchange.order.infra.persistence.mapper
    retry-task:
      rescue:
        enabled: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,liveness,readiness
  endpoint:
    health:
      probes:
        enabled: true
